-- Lumina Classroom schema for Supabase (PostgreSQL)

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  student_id text unique,
  name text not null,
  email text unique,
  phone text unique,
  role text not null check (role in ('teacher', 'student')),
  profile_picture text,
  contact_info text,
  bio text
);

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  teacher_id bigint references public.users(id),
  code text unique not null
);

create table if not exists public.enrollments (
  user_id bigint not null references public.users(id),
  class_id bigint not null references public.classes(id),
  primary key (user_id, class_id)
);

create table if not exists public.assignments (
  id bigint generated by default as identity primary key,
  class_id bigint references public.classes(id),
  title text not null,
  description text,
  due_date text
);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  assignment_id bigint references public.assignments(id),
  student_id bigint references public.users(id),
  content text,
  grade text,
  status text default 'pending',
  submitted_at timestamptz default now()
);

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  class_id bigint references public.classes(id),
  content text not null,
  created_at timestamptz default now()
);

create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id),
  student_id bigint not null references public.users(id),
  attendance_date text not null,
  status text not null check (status in ('present', 'late', 'absent')),
  checked_by bigint references public.users(id),
  checked_at timestamptz default now(),
  unique (class_id, student_id, attendance_date)
);

create table if not exists public.leaderboard_scores (
  class_id bigint not null references public.classes(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  score integer not null default 0,
  streak integer not null default 0,
  best_streak integer not null default 0,
  updated_at timestamptz default now(),
  primary key (class_id, user_id)
);

create table if not exists public.class_games (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  title text not null,
  description text,
  total_questions integer not null default 10,
  time_limit_sec integer not null default 20,
  is_active boolean not null default true,
  created_at timestamptz default now()
);

create table if not exists public.class_game_questions (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  game_id bigint not null references public.class_games(id) on delete cascade,
  question_text text not null,
  choice_a text not null,
  choice_b text not null,
  choice_c text not null,
  choice_d text not null,
  correct_choice text not null check (correct_choice in ('A','B','C','D')),
  display_order integer not null default 1
);

create unique index if not exists idx_users_phone_unique
  on public.users(phone)
  where phone is not null;
